# Run: docker compose -it --rm -e newProjectName=your_project_name generate
# Replace your_project_name with the name of the project you want to generate.
# fx. docker compose -it --rm -e newProjectName=my.test.project generate

# The generated project will be in the generated_projects folder in the current folder. [newProjectName] is the name of the project you want to generate.

services:
  generate:
    image: node:20
    volumes:
      - .:/app
    command: bash -c "cd /app && mkdir generated_projects && ./init.sh -newProjectName $${newProjectName} -destinationPath generated_projects"
