// This file is auto-generated by @hey-api/openapi-ts

import type { CancelablePromise } from './core/CancelablePromise';
import { OpenAPI } from './core/OpenAPI';
import { request as __request } from './core/request';
import type { GetApiV1PackageReferenceProjectExampleResponse } from './types.gen';

export class V1Service {
    /**
     * @returns string OK
     * @throws ApiError
     */
    public static getApiV1PackageReferenceProjectExample(): CancelablePromise<GetApiV1PackageReferenceProjectExampleResponse> {
        return __request(OpenAPI, {
            method: 'GET',
            url: '/api/v1/Package.Reference.Project/example',
            errors: {
                401: 'The resource is protected and requires an authentication token'
            }
        });
    }
    
}